version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t hanzhi227/lambda-docker-test:house  .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push hanzhi227/lambda-docker-test:house
  test:
    docker:
      - image: hanzhi227/lambda-docker-test:np
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

workflows:
#  build-push-docker-and-test:
#    jobs:
#      - build
#      - test:
#          requires:
#            - build
  test-only:
    jobs:
      - test
